### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by 0dikpah** [ArclightTW/Tiny-Reactors#1]
minecraft 1.12.1
Forge 1.12.1-14.221.2485
[crash-2017-10-13_13.39.58-client.txt](https://github.com/ArclightTW/Tiny-Reactors/files/1382489/crash-2017-10-13_13.39.58-client.txt)

**Comment by ArclightTW** [comment]
This was a known issue, conflicting with Tiny Progressions due to some derps on my part across both mods. [Version 0.1.2](https://minecraft.curseforge.com/projects/tiny-reactors/files/2490273) fixes this.
