### ISSUE TITLE
No Inventory Showing

### ISSUE THREAD

**Issue by burlingk** [ArclightTW/Tiny-Reactors#10]
I appear to be running version 0.4.0.

When I right click on the controller, the inventory is showing as empty, so I am unable to fuel the reactor.

**Comment by Kashdeya** [comment]
um what? you do not add fuel to the reactor in the controller. the ores/blocks you place in the middle of the build is the fuel. the controller just controls the reactor.

**Comment by burlingk** [comment]
So, I basically fill in the middle with fuel and it just produces based on that forever?

**Comment by burlingk** [comment]
Build adjusted.  Producing RF.  Preparing to build stuff to attach to it. :)
