### ISSUE TITLE
Crash on Server startup (Linux)

### ISSUE THREAD

**Issue by Jergeric** [ArclightTW/Tiny-Reactors#12]
Minecraft: 1.12.2
Forge: 1.12.2-14.23.0.2542
[crash-2017-11-15_10.33.28-server.txt](https://github.com/ArclightTW/Tiny-Reactors/files/1474218/crash-2017-11-15_10.33.28-server.txt)

**Comment by ArclightTW** [comment]
Goddammit, I know exactly the cause for this... Will fix as urgently as I can manage.

**Comment by ArclightTW** [comment]
v0.5.1 is uploading to fix this crash.
