### ISSUE TITLE
[1.12.2-1.0.8-SNAPSHOT] [BUG] Custom config reagents doesn't work most of time

### ISSUE THREAD

**Issue by LuciusV** [ArclightTW/Tiny-Reactors#13]
__Mod Version:__  
(the version of the mod you are running, per Minecraft's Mods screen or the .jar file directly)  
tinyreactors-1.12.2-1.0.8-SNAPSHOT.jar
EnderCore-1.12.2-0.5.22.jar
EnderIO-1.12.2-5.0.24.jar
Forge 2655

__Java Version:__  
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_161"
OpenJDK Runtime Environment (IcedTea 3.7.0) (Gentoo icedtea-3.7.0)
OpenJDK 64-Bit Server VM (build 25.161-b12, mixed mode)
  
__Issue Overview:__  
Custom config reagents for blocks from EnderIO with same registry but different metadata doesn't work after restart or adding several blocks with same registry
  
__Issue Explanation:__  
This config doesn't work if I add all lines
        enderio:block_alloy [ 0 ] = 36
        enderio:block_alloy [ 1 ] = 256
        enderio:block_alloy [ 2 ] = 1024
        enderio:block_alloy [ 3 ] = 96
        enderio:block_alloy [ 4 ] = 80
        enderio:block_alloy [ 5 ] = 64
        enderio:block_alloy [ 6 ] = 72
        enderio:block_alloy [ 7 ] = 192
        enderio:block_alloy [ 8 ] = 540
Usually if I add them all only last one works (End Steel Block)
If I add only one, for example, Vibrant Alloy enderio:block_alloy [ 2 ] = 1024, it usually works

Also, I've seen some weird changes to another default ores config lines after adding these

__Steps to Recreate:__  
Add these lines to config and make 3x3x3 reactor with 1 material block inside

**Comment by ArclightTW** [comment]
Derp on my part, really.  This has been fixed in my development environment so will be rolled out with version 1.0.9-SNAPSHOT.
