### ISSUE TITLE
Reactor refuses to stay validated upon activation

### ISSUE THREAD

**Issue by GazbonicAcid** [ArclightTW/Tiny-Reactors#13]
Reactor refuses to stay validated upon activation, even when valid.
What besides [mods](https://i.imgur.com/JK2TNPM.png) do I need to get to you to help you trouble-shoot?

**Comment by ArclightTW** [comment]
Are you using v0.5.1? It included a hotfix that should address this.

**Comment by ArclightTW** [comment]
I believe this is fixed so I am going to close this issue due to lack of response.
