### ISSUE TITLE
No recipe

### ISSUE THREAD

**Issue by 0dikpah** [ArclightTW/Tiny-Reactors#2]
I use JEI for recipes but no blocks in this mod can be desplayed with JEI.

**Comment by ArclightTW** [comment]
Interesting... I’ll take a look at this later since all the blocks have got crafting recipes. Thanks for highlighting.

**Comment by 0dikpah** [comment]
awesome :) can't wait to try out this mod

**Comment by ArclightTW** [comment]
@0dikpah can you confirm what versions of JEI and TinyReactors you are using?
My versions are;
TinyReactors - 0.1.2
JEI - 4.8.0

The recipes are working in my dev environment, showing in JEI? :)

**Comment by 0dikpah** [comment]
Im using lates of ur mod and jei_1.12.2-4.7.11.102 (whitch is the latest jei mod that supports minecraft 1.12.1 that i am using and 1.12.2 that you are using)^^

**Comment by ArclightTW** [comment]
Hmm, thanks for highlighting. I just ran a test environment and found that the lang file also isn't working?  Sounds like my build is 1.12.2 compatible only; I'll update CurseForge and see if I can get a back port for 1.12 and 1.12.1 working as soon as possible.  Thanks for highlighting!

**Comment by 0dikpah** [comment]
okay :) if you backporting i will tell you if i found any more problems

**Comment by ArclightTW** [comment]
Just been informed by a fellow model than building in 1.12.2 means the mod won't work properly in 1.12.1 or 1.12 but building in 1.12 will work for 1.12.1 and 1.12.2.  I hate MC sometimes.

SOOOO... I will set up a 1.12 workspace when I'm home (in a couple of hours) and get a fix out for Tiny Reactors that should work for all Minecraft 1.12 versions!

**Comment by ArclightTW** [comment]
Tiny Reactors 0.2.0 now works across all versions of Minecraft 1.12 (1.12 - 1.12.2) and has working recipes, lang files, etc.

**Comment by 0dikpah** [comment]
Thank you very much!
