### ISSUE TITLE
[1.0-SNAPSHOT] [CRASH] Crashed On Loading

### ISSUE THREAD

**Issue by Diamondman121314** [ArclightTW/Tiny-Reactors#2]
**Mod Version**: 1.0-SNAPSHOT
**Java Version**: 1.8.0_172

**Issue Overview**: I was just loading my test pack and it crashed with this.
**Steps To Recreate**: Just loading it.

**Crash Log**: https://pastebin.com/VRZGqjv6

**Comment by ArclightTW** [comment]
Crash due to client-side only functions attempting to be called on the server.  Resolved and upcoming patch to fix.

**Comment by ArclightTW** [comment]
Fixed in 1.0.1-SNAPSHOT
