### ISSUE TITLE
[1.12.2 v0.2.0] Blocks too soft

### ISSUE THREAD

**Issue by VallenFrostweaver** [ArclightTW/Tiny-Reactors#3]
While I do like the ease of removing the blocks with a single click it's a little too easy. A single click removes 2 blocks for me. Also, the fact that an empty hand will destroy the block makes for some frustration of lost materials. Especially if a mob is nearby and you swipe then find half your reactor is missing. ;-;

I would like to suggest to have it at least as hard as netherrack for a fist and pick or perhaps the option to shift+right-click with a pick to instant get the block and it's as hard as obsidian otherwise? This should make it a little more "oops!" proof in either examples.

**Comment by ArclightTW** [comment]
Ah s**t, that's totally my bad; I always forget to add block hardness and resistance. I will look into this!!

**Comment by VallenFrostweaver** [comment]
No worries.

**Comment by ArclightTW** [comment]
Fixed in v0.3.0, currently pending with CurseForge - shift right click with a pickaxe to insta-break.
