### ISSUE TITLE
[Tiny Reactors 1.12.2-1.0.3-SNAPSHOT][CRASH] Crash when using wrench on air vent

### ISSUE THREAD

**Issue by Knito58** [ArclightTW/Tiny-Reactors#5]
__Mod Version:__  
Tiny Reactors 1.12.2-1.0.3-SNAPSHOT

__Java Version:__  
java version "1.8.0_144"
Java(TM) SE Runtime Environment (build 1.8.0_144-b01)
Java HotSpot(TM) Client VM (build 25.144-b01, mixed mode, sharing)

__Issue Overview:__   
Was building an reactor in a 4x4x4 size. The reactor was not valid yet. Made 4 air vents on top side and inserted a diamond fan into each of them. Then wanted to know if everything was right and right clicked a vent with the wrench. The game crashed.

__Crash Log:__  
https://www.dropbox.com/s/olc5lzpx3f8gtxj/crash-2018-05-02_21.17.30-server.txt?dl=0

**Comment by Knito58** [comment]
When writing this issue the game was running with the world where the crash was. After posting the message the game crashed again. Now I did not do anything in the world, I was in the explorer and fiddled with files. The crash log seems to address the same error as above. So it may or may not be an issue with Tiny Reactors as it did not need any action from my side to shut down now. The log does not indicate if TR was involved with that cause. Maybe the unfinished reactor structure is hurting the system? 
Maybe something else?
I don't know. And I cannot address this error to TR.
Therefore I close this issue until next crash.

**Comment by Knito58** [comment]
Now this time I hit escape to remap some keys and the game crashed. The log clearly points at TR this time.
https://www.dropbox.com/s/8pmt8wxhfgquixu/crash-2018-05-02_21.54.34-server.txt?dl=0

**Comment by Knito58** [comment]
And now it crashes on world load. The world is lost atm as I cannot re-enter it.
https://www.dropbox.com/s/v6i9st2wqqy78zs/crash-2018-05-02_22.00.57-server.txt?dl=0

**Comment by ArclightTW** [comment]
Relates to performance impact in #6 - very basic thread implemented to handle validation steps, need to rework logic.

**Comment by ArclightTW** [comment]
I understand this to be fixed in version 1.0.4-SNAPSHOT

**Comment by Knito58** [comment]
Congrats on fixed bug. The world is back again - no more crashes now. I succeeded finally with a valid build which filled an energy cell. But following the wiki I first  put the controller in one of the corners

> "The four corner pillars of the Reactor structure (reaching from bottom to top layer) must be built from Reactor Casing. These blocks can be replaced by Reactor Controllers (1 maximum) and Reactor Transfer Ports on any of the middle layers."

But this did not work. The controller must not be in a corner pillar.
One more note: The reactor blocks break way too easy. Please add some resistance so it gets not destroyed unintendedly (which happened more than once in my case).

Overall this mod gives a good feeling. I like it!

**Comment by Knito58** [comment]
Side note: I put a hopper on a RTP and put 14 diamond blocks into the hopper (all I had). I thought that this would last a while. But the RTP ate all of the blocks and emptied the hopper. Is this intended behaviour? Are they stored inside? Are they gone forever?

**Comment by ArclightTW** [comment]
With regards to the hopper, however, the Reactor Transfer Port can store 9 stacks of items in an internal buffer.  Clicking on the RTP whilst holding a set of valid reactants will insert them all, no need for a hopper.  Clicking on the RTP with an empty hand will remove the last stack and return it to your inventory.  Breaking the RTP will drop all stored contents.

**Comment by ArclightTW** [comment]
Open an issue with any suggestions you have and I'll see what I can do, easier to have a central location :)

**Comment by Knito58** [comment]
Yes Sir!
