### ISSUE TITLE
[1.12.2 v0.2.0] Nether Quartz Ore/Block no RF?

### ISSUE THREAD

**Issue by VallenFrostweaver** [ArclightTW/Tiny-Reactors#5]
According to the description page on Curseforge - Nether Quartz Ore/Block also will produce power. I have had neither or any form of quartz or the ore that I can think of produce any power.

**Comment by ArclightTW** [comment]
I have just tested v0.3.0 with Nether Quartz Ore and Block producing power.  Keep an eye on CurseForge as the new version should be up shortly.

**Comment by ArclightTW** [comment]
Please let me know if this is resolved in the new version and I will close accordingly.

**Comment by VallenFrostweaver** [comment]
Resolved. :)
