### ISSUE TITLE
[1.12, v0.3.0] No recipes in JEI 

### ISSUE THREAD

**Issue by Akiishii** [ArclightTW/Tiny-Reactors#6]
I'm currently using:
JEI: v4.7.11.102
Tiny Reactors: 0.3.0
In Minecraft 1.12.

There are no recipes shown in JEI dunno why. Maybe you can fix that ?

**Comment by Kashdeya** [comment]
This has been fixed in our version and will be working in the next release.

**Comment by Akiishii** [comment]
Great! :)

**Comment by ArclightTW** [comment]
This is fixed in v0.3.1 that is currently uploading.  Let me know once this is resolved and I can close the issue.

**Comment by Akiishii** [comment]
Recipes are working now :)
