### ISSUE TITLE
Adding a capacitor invalidates the structure

### ISSUE THREAD

**Issue by Staegrin** [ArclightTW/Tiny-Reactors#7]
Using latest version 1.1.1

Built A 3x3x3 test reactor with emerald block in the center. Exterior all casings along with 1 capacitor + 1 energy port + 1 controller. On 3 of the 4 sides.
![2017-11-02_01 46 49](https://user-images.githubusercontent.com/8494635/32304468-c0f6cdf8-bf6f-11e7-8983-2bb91e906da7.png)
-> invalid structure
Replace the capacitor with a casing and the structure becomes valid and works.
![2017-11-02_01 49 16](https://user-images.githubusercontent.com/8494635/32304501-1095834a-bf70-11e7-809d-0e3aa0ea2109.png)

Also is it intentional, that when in the UI of either the energy port or the controller that your items in your inventory become invisible /are gone while in the UI?

**Comment by ArclightTW** [comment]
A Capaictor is not a Reactor block, hence being a Capacitor and not a Reactor Capacitor. The Energy Port outputs energy into the Capacitor.

As for the inventory, this is an oversight on my part that I will fix, thanks for pointing out.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
